if(EXISTS "/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/ProgrammingC++/02/Google_Tests_run_cstack[1]_tests.cmake")
  include("/mnt/c/Users/farra/OneDrive/Рабочий стол/C++ files/ProgrammingC++/02/Google_Tests_run_cstack[1]_tests.cmake")
else()
  add_test(Google_Tests_run_cstack_NOT_BUILT Google_Tests_run_cstack_NOT_BUILT)
endif()
